### ISSUE TITLE
person-edit.php: Mail-Adresse Feld

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#114]
Jetzt: Alle möglichen Texte sind als Mail-Adresse möglich

ToBe: Text muss auf @ und Domain-Endung gekennzeichnet werden

**Comment by AlisaaaGru** [comment]
![pferd-edit e-mail](https://user-images.githubusercontent.com/44397960/54078039-99ebce80-42c1-11e9-8a1c-ee27057bba09.jpg)
ist das gemeint ?
