### ISSUE TITLE
person-edit.php: PLZ Länge

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#118]
Jetzt: Die PLZ kann beliebig lang eingegeben werden

ToBe: Fehlermeldung wenn zu lang

**Comment by Kerstin1369** [comment]
ist schwierig zu begrenzen, da verschiedene Länder unterschiedlich lange PLZs haben

**Comment by Kerstin1369** [comment]
Österreich hat zum Beispiel 4 und Schweiz & Lichtenstein auch 4 aber Postintern 6

**Comment by Juliia197** [comment]
Ich hab sie auf 4-5 Stellen im Zuge der Plausichecks begrenzt

**Comment by Kerstin1369** [comment]
Niederlande ist sogar alphanumerisch
