### ISSUE TITLE
pferd-deletet.php: Link anpassen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#120]
Jetzt: Link der Seite ist "pferd-deleted.php"

ToBe: Link der Seite "pferd-delete.php"

**Comment by henrikfiedler** [comment]
Seite deleted wurde renamed in delete. Seite delete wurde renamed in delete_alt. Link auf pferd-show ist angepasst. Link auf pferd ist angepasst, wenn nicht von @AlisaaaGru überschrieben wird
