### ISSUE TITLE
pferd-edit.php: Person löschen PopUp

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#121]
Jetzt: Das PopUp fehlt, wenn eine Person gelöscht wird

ToBe: Das PopUp fragt, ob die Person wirklich gelöscht werden soll

**Comment by ghost** [comment]
das gehört aber nicht in pferd-edit??

**Comment by ghost** [comment]
Oder meinst du bei den Beziehungen? Das ist doch egal.

**Comment by Juliia197** [comment]
Bei Beziehungen meine ich. Es wäre halt für den User besser, wenn alle Löschvorgänge mit einem PopUp versehen sind. 

Die Anleitung dafür kann dir @henrikfiedler zeigen.

**Comment by henrikfiedler** [comment]
https://github.com/Juliia197/HRP/issues/44 hier wäre die Anleitung
