### ISSUE TITLE
pferd-edit.php: Speicherung ohne Beziehung

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#122]
Jetzt: Möchte man eine neue Beziehung hinzufügen und man klickt auf den Button, wird das Pferd gespeichert.

ToBe: Zwischenspeicherung der Daten, aber keine Speicherung des Pferdes ohne Besitzer

**Comment by ghost** [comment]
Ich weiß leider nicht, wie ich das umsetze. Bevor hier mehrere Stunden draufgehen. Ich bezweifle das es dafür Punktabzug gibt

**Comment by Juliia197** [comment]
Das Problem ist nur, wenn oben Daten fehlen oder fehlerhaft sind kommt es zu Problemen. Auch wenn die Box noch nicht zugeordnet wurde. Dies betrifft vor allem das Neuanlegen eines Pferdes

**Comment by Juliia197** [comment]
@Freymuth Ich übernehme
