### ISSUE TITLE
pferd-edit.php: Besitzer löschen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#123]
Jetzt: Besitzer kann gelöscht werden und Pferd ohne Besitzer gespeichert werden

ToBe: Besitzer kann nur geändert werden, aber nicht gelöscht werden

**Comment by ghost** [comment]
wüsste nicht wie ich das umsetzen kann

**Comment by Juliia197** [comment]
Mach doch eine Ausnahme, dass die Rolle Besitzer als oberste Zeile in der Tabelle erscheint und dahinter man nur auswählen kann und nicht die Rolle verändert werden kann.

**Comment by Juliia197** [comment]
Erübrigt sich. Ich übernehme
