### ISSUE TITLE
pferd-show.php: Boxenpreis

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#127]
Jetzt: Kein Boxenpreis zu Pferd wird angezeigt

ToBe: Boxenpreis anzeigen

**Comment by henrikfiedler** [comment]
Abfrage funktioniert. Welche Einheit hat denn der Boxenpreis?

**Comment by Juliia197** [comment]
Euro

**Comment by henrikfiedler** [comment]
Euro/Monat?

**Comment by Juliia197** [comment]
Ja

**Comment by henrikfiedler** [comment]
Done!
