### ISSUE TITLE
Allgemein: Test auf SQL-Injections

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#128]
Alle bitte einmal testen auf SQL injections

**Comment by henrikfiedler** [comment]
So, also hier eine hoffentlich verständliche Anleitung zu Prepared Statements

Beispiel für Select-Statement bei der Gehöft-ID-Abfrage

`$id_pferd = $_GET["id_pferd"];` Speichern (des Parameters) als Variable
`$query = "SELECT id_gehoeft FROM box WHERE id_pferd = ?";` Speichern der query in eine Variable (gesondert). "?" kennzeichnet Variable die eingefügt werden soll.
`$auth_sql = $conn->prepare($query);` Vorbereiten der Query. Query wird übergeben. (kann auch ohne Variable direkt reingeschrieben werden).
`$auth_sql->bind_param("i", $id_pferd);` Vorgeben der einzusetzenden Variablen. Davor wird festgelegt, welche(n) Typ(en) die Variablen haben dürfen. "i" = Integer, "s" = String, "d" = Double, "b" = BLOB. Kombination auch möglich, bspw. "si" = Strings+Integers. Anschließend die zu übergebenen Variablen mit Kommatrennung
`$auth_sql->execute();`. Ausführung der Query.
`$result = $auth_sql->get_result();` Beschaffung des Ergebnisses
`$auth_result = $result->fetch_assoc();` Fetch wie gewohnt.
  
`if ($auth_result["id_gehoeft"] == $id_gehoeft) {`
`  $auth = true;`
`}`

`$auth_sql->close();` Schließen der Query.

Bei Inserts, Deletes, Updates muss die Query nach dem Execute nur noch geschlossen werden, man braucht ja idR dann auch kein Result.
Also:
`...`
`$auth_sql->execute();`
`$auth_sql->close();`


Nochmal der Code ohne Anmerkungen:

`$id_pferd = $_GET["id_pferd"];`
`$query = "SELECT id_gehoeft FROM box WHERE id_pferd = ?";`
`$auth_sql = $conn->prepare($query);`
`$auth_sql->bind_param("i", $id_pferd);`
`$auth_sql->execute();`
`$result = $auth_sql->get_result();`
`$auth_result = $result->fetch_assoc();`

`if ($auth_result["id_gehoeft"] == $id_gehoeft) {`
`  $auth = true;`
`}`

`$auth_sql->close();`

**Comment by henrikfiedler** [comment]
und dann solltet ihr das eben genau dieses Beispiel noch anwenden. Das was ich Donnerstag Mittag bei allen eingefügt hab, sollte dann nochmal prepared gebaut werden.

Als Beispiel bei **person-edit**

Aktuell - Diesen Teil ersetzen

`$auth_sql = "SELECT id_gehoeft FROM person WHERE id_person = " . $_GET['id_person'] . "";`
`$auth_result =  $conn->query($auth_sql);`
`$auth_result = $auth_result->fetch_assoc();`
	    
`if ($auth_result['id_gehoeft'] == $id_gehoeft) {`
`$auth = true;`
`}`

Hierdurch Ersetzen 

`$id_person = $_GET["id_person"];`
`$query = "SELECT id_gehoeft FROM person WHERE id_person = ?";`
`$auth_sql = $conn->prepare($query);`
`$auth_sql->bind_param("i", $id_person);`
`$auth_sql->execute();`
`$result = $auth_sql->get_result();`
`$auth_result = $result->fetch_assoc();`

`if ($auth_result["id_gehoeft"] == $id_gehoeft) {`
`$auth = true;`
`}`

`$auth_sql->close();`

Bitte beachten, dass ihr die Variable und die Query auf euer Gebiet anpassen müsst. Bspw bei **box** muss die **id_box** aus der Tabelle **box** abgefragt werden. Solltet ihr hinbekommen. Bei Fragen einfach melden.

**Comment by Juliia197** [comment]
Bei mehreren Parametern, die eingefügt werden müssen sind 2 Dinge zu beachten:
1. die Typen müssen die gleiche Anzahl an Elementen haben wie die Elemente, die du einbinden möchtest. Willst du also 2 Variablen einfügen, die erste Integer, die zweite String, dann sieht dein String so aus: "is"
2. Die Parameter müssen mit Komma getrennt in der richtigen Reihenfolge hinten angefügt werden
