### ISSUE TITLE
Allgemein: id-gehoeft in Abfragen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#129]
Jetzt: id_gehoeft ist entweder nicht gesetzt oder automatisch auf 1 gesetzt in Abfragen und allem

ToBe: id_gehoeft abhängig von der SESSION machen

**Comment by henrikfiedler** [comment]
Ich schreib hier immer mal rein, wie weit ich momentan bin. Werd dann aber erst am Montag weitermachen können. Ihr könntet eure eigenen Seiten bereits anfangen umzubauen.

**login.php**
- Überprüfung wie vielen Gehöften (0,1,>1) ein Benutzer zugeordnet ist in Tabelle benutzer_verwaltet_gehoeft
- Abfragen der id_gehoeft und übergeben an session

**admin.php (neue Seite)**
- Zuordnen von Benutzern zu einem Gehöft und Übergabe an benutzer_added.php
Funktionalität steht, aber noch sehr rudimentär

**benutzer_added.php (neue Seite)**
- Überprüfung ob Benutzer bereits dem Gehöft zugeordnet ist
- Zuordnung zum Gehöft

**Comment by henrikfiedler** [comment]
Wer dann mit dem umgebauten login arbeiten will muss beachten, dass standardmäßig nur die benutzer 1 und 2 einem Gehöft zugeordnet sind. mit eurem erstellten benutzer bekommt ihr dadurch keinen zugriff mehr auf die website.
Dazu müsst ihr dann auf die **admin.php** gehen, die noch nicht die if Bedingung beinhaltet, ob ihr eingeloggt seid. daher eure benutzer id einem Gehöft zuordnen und dann sollte es eine neue Zeile in der Tabelle benutzer_verwaltet_gehöft geben.

**Comment by henrikfiedler** [comment]
müsste ja mittlerweile auch auf allen Seiten passen, ich stell's mal auf Review
