### ISSUE TITLE
Alle Tabellen: Class table-hover hinzufügen

### ISSUE THREAD

**Issue by henrikfiedler** [Juliia197/HRP#132]
Müsste im master auf der Seite pferd-show anschaubar sein, find ich recht schick. Wird einfach nur eine Klasse dem table hinzugefügt, welche dann beim hover über eine Zeile die bestimmte Zeile anders färbt.

`<table class="table-hover">`

**Comment by Juliia197** [comment]
@henrikfiedler wird dieser Hover dann beim Löschen auch angezeigt?

**Comment by henrikfiedler** [comment]
Ja, dadurch wäre auch klar, welche Zeile man dazu angewählt hat. Zumindest vom PC aus

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/33574047/53683901-d38f6900-3d06-11e9-8ad2-49fd99435a2d.png">

**Comment by Kerstin1369** [comment]
Ich finde das ist eine gute Idee, können wir gerne so machen

**Comment by Juliia197** [comment]
Wird umgesetzt
