### ISSUE TITLE
pferd-edit.php: Pferd anlegen mit Box

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#136]
Jetzt: Pferd kann auch ohne Box angelegt werden

ToBe: Pferd muss immer Box zugeordnet sein

**Comment by henrikfiedler** [comment]
hab ich gefixed. hab einfach eine "required" zum <input> hinzugefügt. 
EDIT: funktioniert dann auch in soweit, dass das Pferd nicht direkt gespeichert wird, wenn man eine Person hinzufügt, aber noch keine Box ausgewählt wurde

**Comment by henrikfiedler** [comment]
okay, hab ich doch nicht gefixed, durch die mehreren required gibts Probleme beim abschicken
