### ISSUE TITLE
pferd-edit.php: Neues Pferd anlegen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#146]
Jetzt: Nur Besitzer oder Box kann zugewiesen werden, wenn ein neues Pferd erstellt wird

ToBe: Besitzer und Box in einem Rutsch zuweisen

**Comment by henrikfiedler** [comment]
Zusätzlich: Pferd muss aktuell zwischengespeichert werden, bevor es einer Box zugewiesen werden kann. Allerdings wäre das Pferd nach dem Zwischenspeichern nicht mehr auffindbar, da es über die Box dem Gehöft zugewiesen wird
