### ISSUE TITLE
Plausichecks

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#152]
Geburtsdatum Person
Geburtsdatum Pferd: 1970
Einstelldatum
Lieferdatum/Ankunft Hof: ab 1.1.2018
Preis
Menge
Gewicht
Boxenpreis: 0<x<5000
Passnummer Länge
PLZ: 4-5

**Comment by AlisaaaGru** [comment]
Pass: müsste 15 Stellig sein

**Comment by AlisaaaGru** [comment]
Größe 35 cm-210 cm
Gewicht 3kg-1543

**Comment by AlisaaaGru** [comment]
Menge -> sollte nciht null sein
-> kosten nicht negativ

**Comment by Juliia197** [comment]
box-edit:
- Boxenpreis: 0-2000

gut-edit:
- Bezeichnung: 1-45 Zeichen
- Lieferdatum: ab 1.10.2018
- Menge: 1 - 10000
- Einkaufspreis: 0,01 - 300

Pferd-edit:
- Bezeichnung: 1-45 Zeichen
- Gewicht: 3-1543
- Größe: 35-210
- Passnummer: 15-stellig
- Geburtsdatum: ab 1.1.1980
- Ankunft: ab 1.10.2018

person-edit:
- Vorname: 1-45 Zeichen
- Nachname: 1-45 Zeichen
- E-Mail: e-mail
- Telefonnummer: 9-45 Zeichen
- Geburtsdatum: ab 1.1.1900
- Straße: 1-45 Zeichen
- Hausnummer: 1-45 Zeichen
- PLZ: 4-5 stellig
- Ortschaft: 1-45 Zeichen
- Land: 1-2 Zeichen
