### ISSUE TITLE
Diskussion: Farbe der Seite (Balken oben und Links)

### ISSUE THREAD

**Issue by AlisaaaGru** [Juliia197/HRP#155]
Auf login in Braun der rest in Grau/Schwarz die Balken evtl in der Selben Farbe wie login?

**Comment by henrikfiedler** [comment]
ich würd's so lassen wie's ist. Auf der login find ich's schön, aber auf der Hauptseite find ich braun nicht so ansprechend

**Comment by AlisaaaGru** [comment]
naja ich finde wir müssen das Braun wieder aufgreifen
sonst ist es doof das es auf der Login seite ist

**Comment by Juliia197** [comment]
Lassen wir es so wegen Zeitgründen und Funktionalität
