### ISSUE TITLE
Registrierungs- und Login-Prozess

### ISSUE THREAD

**Issue by henrikfiedler** [Juliia197/HRP#163]
Also, um unsere Erweiterung auf mehrere Gehöfte zu vervollständigen müssen wir die Registrierung abändern und dementsprechend auch mal wieder die Datenstruktur.
Wir haben folgende Voraussetzungen, dass es so momentan nicht funktioniert. Eine reale Person wird mehrfach in der Datenbank, eben für mehrere Gehöfte vorkommen. Ein Benutzer kann mehrere Gehöfte verwalten.

Daher müssen wir folgende Änderungen machen:
**E-Mail-Adresse** wird als Attribut in die Tabelle Benutzer eingefügt, so dass wir eine klassische User-Tabelle haben.
**id_person** wird als Attribut aus der Tabelle Benutzer entfernt, so dass wir den Benutzer von der Person entkoppeln.

### Wie genau läuft dann der Registrierungsprozess ab?

Ein Nutzer registriert sich ganz normal mit seiner E-Mail-Adresse.
Anschließend gibt es 2 Optionen:
Option 1: Es gibt noch keinen einzigen Gehöftverwalter: Dann müssen wir einen ersten Gehöftverwalter über die admin.php dem Gehöft zuweisen
Option 2: Es gibt bereits mindestens einen Gehöftverwalter: Dann kann ein Gehöftverwalter einen Benutzer zum Gehöft über Eingabe der E-Mail zu diesem Gehöft zuweisen.

Das Löschen von Gehöftverwaltern müssten dann wiederum wir übernehmen, da es (noch) keinen Superuser mit Sonderrechten gibt.

Das automatische Anlegen des Benutzers als Person fällt weg, da das sonst zu komplex und aktuell die Person sowieso immer noch überarbeitet werden muss, da bspw. Adresse, Telefonnummer, etc. fehlen.

**Comment by henrikfiedler** [comment]
Und wir sollten noch das Attribut reg**e**strierungsdatum in reg**i**strierungsdatum umbenennen, so vong deutsche Rechtschreibung her.

**Comment by Juliia197** [comment]
Jap ist alles genehmigt. Allerdings frage ich mich, ob sich dann nicht einfach jemand registrieren kann und sich dann in das Gehöft einschleichen kann. Sprich er registriert sich, sagt Hallo ich bin von Gehöft 1 und in Wirklichkeit ist er es nicht. Wie würdest du das vermeiden?

**Comment by henrikfiedler** [comment]
Ich denk mal die Kommunikation würde da auf nem anderen Weg ablaufen. Also ein erster Verwalter würde ja sowieso bei uns anfragen müssen. Und weitere Verwalter kennt ja der Gehöftbesitzer und muss dann halt von denen direkt die E-Mail-Adresse bekommen.

Ansonsten:
Über die E-Mail könnte ich ja jemanden eindeutig identifizieren. Hab mich da grade noch zwecks Aktivierungsmail eingelesen, das wäre auch gar nicht mal so schwer. Wären dann nochmal 2 zusätzliche Attribute und

**Comment by henrikfiedler** [comment]
### Änderungen

- Attribut email in benutzer hinzufügen (in der Reihenfolge vor passwort) (1 email darf nur zu 1 benutzer gehören)
- Attribut aktivierungscode in benutzer hinzufügen (gleiches Feld wie Passwort)
- Attribut aktiviert in benutzer hinzufügen (boolean, also true/false, ja/nein, 1/0)
- Attribut regestrierungsdatum in registrierungsdatum umbenennen (Rechtschreibfehler)
- Attribut id_person in benutzer entfernen ("Entkopplung" von Person und Benutzer)

**Comment by Juliia197** [comment]
> ### Änderungen
> * Attribut email in benutzer hinzufügen (in der Reihenfolge vor passwort) (1 email darf nur zu 1 benutzer gehören)
> * Attribut aktivierungscode in benutzer hinzufügen (gleiches Feld wie Passwort)
> * Attribut aktiviert in benutzer hinzufügen (boolean, also true/false, ja/nein, 1/0)
> * Attribut regestrierungsdatum in registrierungsdatum umbenennen (Rechtschreibfehler)
> * Attribut id_person in benutzer entfernen ("Entkopplung" von Person und Benutzer)

@Kerstin1369

**Comment by Kerstin1369** [comment]
ist erledigt. Ich hoffe das passt so. aktivierungscode habe ich auf NOT NULL, weil ich nicht wusste wie genau die funktion dann späer aussieht, wenn NULL möglich sein soll dann eben Bescheid geben. das Feld "aktiviert" ist ein tinyint(1), da es in mySQL kein richtiges BOOLEAN gibt. Der Wert 0 steht dann für false und alles >=1 steht für true

**Comment by Juliia197** [comment]
@henrikfiedler Automatisch die erste Mail versenden

**Comment by henrikfiedler** [comment]
Also Registrierung und Login ist soweit fertig.
Allerdings muss es hier Unterschiede im Code geben, wenn lokal oder serverseitig registriert wird.
Für die Aktivierung müsst ihr eine Variable auf euren localhost angleichen, damit der Aktivierungslink funktioniert.
**in register.php**
`//Nicht-Passende Links auskommentieren`
`//$link_base = "hrp-projekt.de/activate.php";`
`//$link_base = "localhost/HRP/activate.php";`
`$link_base = "henriks-macbook-pro.local/HRP/activate.php";`

auf der activate.php wird dann per echo der Aktivierungslink auf der Seite ausgegeben, da lokal keine Mail versendet werden kann. Den Aktivierungslink dann einfach kopieren und einmal ausführen, dann sollte der Account aktiviert sein

**Comment by henrikfiedler** [comment]
Aktuell sind **register.php** und **activate.php** im Online-Betrieb. Daher müsste ihr bei der Entwicklung aufm localhost 2 Sachen ändern.

**register.php**
die richtige $link_base für euch auswählen und die anderen auskommentieren.
`//Nicht-Passende Links auskommentieren`
`$link_base = "https://wwww.hrp-projekt.de/activate.php";`
`//$link_base = "localhost/HRP/activate.php";`
`//$link_base = "henriks-macbook-pro.local/HRP/activate.php";`
zu
`//Nicht-Passende Links auskommentieren`
`//$link_base = "https://wwww.hrp-projekt.de/activate.php";`
`$link_base = "localhost/HRP/activate.php";`
`//$link_base = "henriks-macbook-pro.local/HRP/activate.php";`

**activate.php**
in Zeile 69 den Kommentar rausnehmen
`//echo $aktivierungslink;`
zu
`echo $aktivierungslink;`
