### ISSUE TITLE
person-show.php DataTable und Überschrift

### ISSUE THREAD

**Issue by henrikfiedler** [Juliia197/HRP#168]
DataTable funktioniert nicht richtig und Überschrift für die Tabelle wäre auch ganz nett (Vorschlag: "Pferde")

**Comment by AlisaaaGru** [comment]
in wie weit funktioniert die tabelle nicht ?

**Comment by henrikfiedler** [comment]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/33574047/54084807-bf1a2480-4335-11e9-9b0b-6eaf8ff0fa15.png">

sieht so aus.

sollte so aussehen:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/33574047/54084815-d527e500-4335-11e9-8945-8000ab344dbd.png">

**Comment by henrikfiedler** [comment]
Also ich hab's dann mal gefixed. Dir hat das script für Bootstrap 4-DataTables gefehlt. Ich hab's dann wie bei mir in der person-show gemacht, dass es nicht über die ID "dataTable", sondern über die Klasse "display" den deutschen DataTable bekommt. Die ID "dataTable1" auch bitte so lassen, ich hab sonst ne Fehlermeldung bekommen, aber funktioniert jetzt.

<img width="3002" alt="image" src="https://user-images.githubusercontent.com/33574047/54398064-f29fda80-46b8-11e9-9c96-77783ba44c6f.png">

**Comment by Juliia197** [comment]
Ist noch nicht oben oder?

**Comment by henrikfiedler** [comment]
Ja, aber schick doch sogar extra nen Screenshot mit rein -.-

**Comment by Juliia197** [comment]
Ja hat sich erledigt hab das vorhin mit @AlisaaaGru gelöst... War ne 2 zu viel
