### ISSUE TITLE
Benutzer zu Gehöft hinzufügen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#195]
Seite Gehöft zu Benutzer hinzufügen Design anpassen

**Comment by henrikfiedler** [comment]
sieht jetzt so aus. Ich hätte es dann "Gehöftverwaltung benannt"

<img width="3004" alt="image" src="https://user-images.githubusercontent.com/33574047/54121614-35cd2580-43fb-11e9-80ae-71d908124387.png">

Sollte ich dann den Button "Benutzer zum Gehöft hinzufügen" auf der Gehöftseite vielleicht dann auch noch in "Gehöftverwaltung umbenennen und grau/blau machen?

<img width="2768" alt="image" src="https://user-images.githubusercontent.com/33574047/54121660-58f7d500-43fb-11e9-9610-3473f4d4b761.png">

**Comment by henrikfiedler** [comment]
Bei grau ist halt wieder das Ding, dass das zu wenig raussticht, würd ihn vielleicht lieber blau machen. Ist schwierig von der Farbe her.

<img width="2769" alt="image" src="https://user-images.githubusercontent.com/33574047/54121736-85abec80-43fb-11e9-86f7-ea1daed29274.png">
