### ISSUE TITLE
Allgemein: Seitz User Accounts

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#199]
Seitz bekommt 2 Accounts:
1. Admin (mit allen Rechten und Zugriff auf min. 2 Gehöfte)
2. Benutzer (mit Zugriff auf 1 Gehöft)

**Comment by henrikfiedler** [comment]
E-Mail-Adressen sind erstellt, Accounts müssen online noch angelegt, aktiviert und zugeordnet werden.
