### ISSUE TITLE
Bestand manuell aktualisieren/buchen

### ISSUE THREAD

**Issue by henrikfiedler** [Juliia197/HRP#207]
### Vorschlag
Man kann die Bestände manuell aktualisieren, um zum einen, wenn ein neues Gehöft angelegt wird, einen **Anfangsbestand** zu buchen und zum anderen, wenn die Berechnung vom Ist-Verbrauch stark abweicht, den **Bestand anzugleichen**

**Comment by henrikfiedler** [comment]
Also für die Anfangsbestände wär's natürlich möglich, einfach 4 kostenfreie Lieferungen anzusetzen. Die Option, die Bestände zu manuell aktualisieren, könnte man aber trotzdem noch diskutieren.

**Comment by Juliia197** [comment]
Ist aus Inventursicht bestimmt keine schlechte Idee. Auf der anderen Seite ist immer noch das Problem, dass wir das ganze am Mittwoch in einer Woche abgeben müssen

**Comment by henrikfiedler** [comment]
würde ich dann übernehmen, falls noch keiner angefangen hat. Dann einfach nur die Bestände überschreiben und das heutige Datum setzen.

**Comment by henrikfiedler** [comment]
done! noch nicht im Master und ein Button sollte dann noch auf gueter.php

**Comment by henrikfiedler** [comment]
ist im Master
