### ISSUE TITLE
Allgemein: Logout Button

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#233]
Jetzt: Auf manchen Seiten will der Logout Button nicht funktionieren

ToBe: funktionierender Logout Button

**Comment by henrikfiedler** [comment]
da bin ich ein paar Seiten durchgegangen und hab's angepasst

**Comment by Juliia197** [comment]
alle oder ein paar?

**Comment by henrikfiedler** [comment]
die, an denen ich eh gearbeitet hab. also die admin-seiten undso

Impressum hab ich grade noch angepasst, ist aber noch nicht im Master
