### ISSUE TITLE
Allgemein: Alle Seiten kommentieren

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#244]
Jeder kommentiert seine Seiten

**Comment by Juliia197** [comment]
box-edit
box-delete
dashboard
gehoeft
login - Bestandsveränderung

erledigt

**Comment by henrikfiedler** [comment]
login
register
activate
admin-*
gueter-bestand
gueter-bestand-edit
gehoeft-benutzer
gehoeft-benutzer-added
pferd-show
