### ISSUE TITLE
Impressum: Herausnehmen Logout + PW ändern

### ISSUE THREAD

**Issue by Kerstin1369** [Juliia197/HRP#298]
wenn man ausgeloogt auf das im Impressum zugreift sieht es so aus als wäre man eingeloggt obwohl man es gar nicht ist

**Comment by Juliia197** [comment]
Logout und PW-Ändern rausnehmen bei Impressum wenn nicht eingeloggt

**Comment by AlisaaaGru** [comment]
-> Logout link raus  geht neu auf siehe login target=....
