### ISSUE TITLE
person-edit.php: Lieferantenfunktion mehrere Probleme

### ISSUE THREAD

**Issue by Kerstin1369** [Juliia197/HRP#300]
man kann eine Person mehrfach zum Lieferanten machen

**Comment by Kerstin1369** [comment]
Personen die zwei mal Lieferant sind können auch nicht mehr gelöscht ewrden

**Comment by Juliia197** [comment]
Haken wird nicht angezeigt, wenn die Person schon Lieferant ist. Es wird aber kein neuer Datensatz angelegt
