### ISSUE TITLE
Pferd edit-> siehe Bild 

### ISSUE THREAD

**Issue by AlisaaaGru** [Juliia197/HRP#306]
![Pferd erstellen](https://user-images.githubusercontent.com/44397960/54480490-2c8fee80-4829-11e9-9d76-5b1ab73e0642.jpg)

**Comment by ghost** [comment]
Bei dir wird da nichts angezeigt? Schau nochmal nach... Bei mir geht das einwandfrei, ein neues Pferd zu erstellen.

**Comment by Juliia197** [comment]
Funktioniert bei mir.
