### ISSUE TITLE
Person-/Pferd-Show und Person-/Pferd-Delete - Löschen mit Zwischenschritt über JS-Alert

### ISSUE THREAD

**Issue by henrikfiedler** [Juliia197/HRP#44]
@AlisaaaGru @henrikfiedler 

bei Druck auf Lösch-Button JS-Alert mit Bestätigung zum Löschen

@henrikfiedler übernimmt, @AlisaaaGru kann dann rein kopieren

**Comment by henrikfiedler** [comment]
hinzufügen einer onclick-Funktion
`<a class=\"btn btn-secondary\" href=\"pferd-deleted.php?id_pferd=" . $row_p['id_pferd'] . "\" onclick='return checkDelete()'>Löschen</a>`

hinzufügen der JS-Funktion
`<script>
      function checkDelete(){
        return confirm('Pferd endgültig löschen?')
      }
    </script>`

**Comment by ghost** [comment]
Henrik übersichtsseite pferd
