### ISSUE TITLE
Person bearbeiten - Design

### ISSUE THREAD

**Issue by ghost** [Juliia197/HRP#48]
Müssten wir einheitlich machen. Ich habe bei mir jeweils noch Abstand zwischen den Feldern drin. Finde ich besser als alles zusammengepresst. 

http://prntscr.com/mptnxv
https://prnt.sc/mptnin

**Comment by AlisaaaGru** [comment]
wie hast du die abstände reingemacht -> sollten ja die gleichen sein

**Comment by ghost** [comment]
Kannst in HTML einfach ein `<br />` reinhauen. 
Sprich, einen Zeilenumbruch.

**Comment by ghost** [comment]
Sieht besser aus.
