### ISSUE TITLE
Person löschen - unvollständige Meldung

### ISSUE THREAD

**Issue by ghost** [Juliia197/HRP#61]
Wenn ich eine Person lösche, das Löschen bestätige, werde ich auf Seite ohne design weitergeleitet, wo eine Meldung steht das die Adresse im System verbleibt. 

Das sieht sehr unvollständig aus

**Comment by AlisaaaGru** [comment]
Das sollte anders sein,

**Comment by AlisaaaGru** [comment]
die meldung müsste raus sein außer du hast das dokument überschrieben, die leere seite ist absicht

**Comment by ghost** [comment]
Sieht behoben aus.
