### ISSUE TITLE
gueter.php: Button Lieferungen

### ISSUE THREAD

**Issue by Juliia197** [Juliia197/HRP#97]
Jetzt: Der Button Lieferungen ist aus dem Zusammenhang gerissen und steht einfach nur so da

ToBe: Schlüssigere Darstellung des Buttons

**Comment by AlisaaaGru** [comment]
wie wäre es wenn unter den Beständen nen segment kommt  mit hier geht es zu den Lieferungen oder so ? oder evtl auch darüber

andere Vorschläge?

**Comment by Juliia197** [comment]
Oder Zu den Lieferungen als Beschriftung

**Comment by Juliia197** [comment]
@AlisaaaGru  Zu den Lieferungen
